# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chapter3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import shutil
import CommonUtil

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picLabel = QtWidgets.QLabel(self.centralwidget)
        self.picLabel.setGeometry(QtCore.QRect(140, 40, 521, 331))
        self.picLabel.setText("")
        self.picLabel.setObjectName("picLabel")
        self.picLabel.setPixmap(QtGui.QPixmap(CommonUtil.resource_path("./resource/image/moto.png")))

        self.textLabel = QtWidgets.QLabel(self.centralwidget)
        self.textLabel.setGeometry(QtCore.QRect(280, 440, 241, 16))
        self.textLabel.setObjectName("textLabel")
        self.btnGoodBye = QtWidgets.QPushButton(self.centralwidget)
        self.btnGoodBye.setGeometry(QtCore.QRect(340, 480, 93, 28))
        self.btnGoodBye.setObjectName("btnGoodBye")
        self.btnGoodBye.clicked.connect(lambda: self.btn_goodbye(MainWindow))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.textLabel.setText(_translate("MainWindow", "恭喜你到了这里，送你一辆小摩托"))
        self.btnGoodBye.setText(_translate("MainWindow", "再见"))

    def btn_goodbye(self, mainWindow):
        resp = QtWidgets.QMessageBox.information(mainWindow, "提示", "Hold On!",
                                                 QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                                                 QtWidgets.QMessageBox.Yes)
        if resp == QtWidgets.QMessageBox.Yes:
            shutil.copyfile(CommonUtil.resource_path("./resource/txt/storm.txt"), "storm.txt")
            QtWidgets.QMessageBox.information(mainWindow, "提示", "fine,还没完，打开你桌面的storm.txt文件，查看最后的彩蛋~")
            QtWidgets.QMessageBox.information(mainWindow, "提示", "Good Day & Night~")